# https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#configuring-automatically-generated-release-notes

changelog:
  exclude:
    labels:
      - "changelog:skip"
      - "changelog:repository"
  categories:
    - title: Solidus
      labels:
        - "changelog:solidus"
    - title: Solidus Core
      labels:
        - "changelog:solidus_core"
    - title: Solidus Admin
      labels:
        - "changelog:solidus_admin"
    - title: Solidus Backend
      labels:
        - "changelog:solidus_backend"
    - title: Solidus API
      labels:
        - "changelog:solidus_api"
    - title: Solidus Sample
      labels:
        - "changelog:solidus_sample"
